<?php
/**
 * WordPress plugin Admin Patterns that contains design patterns library
 * to help with developing plugins that perfectly fit into WordPress.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @link https://github.com/ondrejd/odwp-adminpatterns for the canonical source repository
 * @package odwp-adminpatterns
 * @since 0.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

use \com\ondrejd\adminpatterns\Snippets_Manager;

?><div class="wrap">

    <h1><?php _e( 'Forms', ODWPAP_DOMAIN ) ?></h1>

	<h3 class="screen-reader-text"><?php _e( 'List of Contents', ODWPAP_DOMAIN ) ?></h3>
	<ul class="subsubsub">
		<li><b><?php _e( 'Contents:', ODWPAP_DOMAIN ) ?></b> </li>
		<li><a href="#br-helper_functions"><?php _e( 'Helper functions', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-text_input"><?php _e( 'Text input', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-textarea"><?php _e( 'Textarea', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-select"><?php _e( 'Select element', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-multi_select"><?php _e( 'Multiple select', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-radio_buttons"><?php _e( 'Radio buttons', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-checkbox"><?php _e( 'Checkbox', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-checkbox_array"><?php _e( 'Array of checkboxes', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-html5"><?php _e( 'Fieldset and HTML5 elements', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-datetime"><?php _e( 'Datetime elements', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-others"><?php _e( 'Other elements', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-buttons"><?php _e( 'Buttons', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-form_table"><?php _e( 'Form table', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-nonce"><?php _e( 'NONCE field', ODWPAP_DOMAIN ) ?></a></li>
	</ul>

    <!-- Helper functions -->
    <br id="br-helper_functions" class="clear" />
    <h2><?php _e( 'Helper functions', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?php printf( __( '%1$sWordPress%2$s contains three helper functions for rendering %3$sdisabled%4$s, %3$schecked%4$s or %3$sselected%4$s attributes:', ODWPAP_DOMAIN ), '<strong>', '</strong>', '<code>', '</code>' ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/helper-functions-1' ) ?>
        <p><?php _e( 'So instead of writing something like this:', ODWPAP_DOMAIN ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/helper-functions-2' ) ?>
        <p><?php _e( 'You can do just this:', ODWPAP_DOMAIN ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/helper-functions-3' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Text input -->
    <br id="br-text_input" class="clear" />
    <h2><?php _e( 'Text input', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <input type="text" name="input-text" placeholder="Text">
	    <?php Snippets_Manager::render_snippet( 'forms/text-input' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Textarea -->
    <br id="br-textarea" class="clear" />
    <h2><?php _e( 'Textarea', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <textarea name="textarea" class="large-text">Sample text</textarea>
	    <?php Snippets_Manager::render_snippet( 'forms/textarea' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Select -->
    <br id="br-select" class="clear" />
    <h2><?php _e( 'Select', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <select name="select">
            <option>Option 1</option>
            <option>Option 2</option>
            <option>Option 3</option>
        </select>
	    <?php Snippets_Manager::render_snippet( 'forms/select' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Multiple select -->
    <br id="br-multi_select" class="clear" />
    <h2><?php _e( 'Multiple select', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <select name="multi-select" multiple="multiple">
            <option>Option 1</option>
            <option>Option 2</option>
            <option>Option 3</option>
            <option>Option 4</option>
            <option>Option 5</option>
            <option>Option 6</option>
        </select>
	    <?php Snippets_Manager::render_snippet( 'forms/multi-select' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Radio buttons -->
    <br id="br-radio_buttons" class="clear" />
    <h2><?php _e( 'Radio buttons', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <input type="radio" name="radio-buttons" value="option-1"/> Option 1 <br>
        <input type="radio" name="radio-buttons" value="option-2"/> Option 2 <br>
        <input type="radio" name="radio-buttons" value="option-3"/> Option 3 <br>
        <input type="radio" name="radio-buttons" value="option-4"/> Option 4
	    <?php Snippets_Manager::render_snippet( 'forms/radio-buttons' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Checkbox -->
    <br id="br-checkbox" class="clear" />
    <h2><?php _e( 'Checkbox', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <input type="checkbox" name="input-checkbox" /> Option 1
	    <?php Snippets_Manager::render_snippet( 'forms/checkbox' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Array of checkboxes -->
    <br id="br-checkbox_array" class="clear" />
    <h2><?php _e( 'Array of checkboxes', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <input type="checkbox" name="checkbox-array[]" value="option-1"> Option 1<br>
        <input type="checkbox" name="checkbox-array[]" value="option-2"> Option 2<br>
        <input type="checkbox" name="checkbox-array[]" value="option-3"> Option 3
	    <?php Snippets_Manager::render_snippet( 'forms/checkbox-array' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Fieldset and HTML5 elements -->
    <br id="br-datetime" class="clear" />
    <h2><?php _e( 'Fieldset and <br>HTML5 elements', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <fieldset>
            <legend><?php _e( 'Legend', ODWPAP_DOMAIN ) ?></legend>
            <input type="email" placeholder="<?php _e( 'Email', ODWPAP_DOMAIN ) ?>" /> <?php _e( 'Email', ODWPAP_DOMAIN ) ?><br>
            <input type="search" placeholder="<?php _e( 'Search', ODWPAP_DOMAIN ) ?>" /> <?php _e( 'Search', ODWPAP_DOMAIN ) ?><br>
            <input type="tel" placeholder="<?php _e( 'Telephone', ODWPAP_DOMAIN ) ?>" /> <?php _e( 'Telephone', ODWPAP_DOMAIN ) ?><br>
            <input type="text" placeholder="Text" /> Text<br>
            <input type="url" placeholder="<?php _e( 'URL', ODWPAP_DOMAIN ) ?>" /> <?php _e( 'URL', ODWPAP_DOMAIN ) ?><br>
        </fieldset>
	    <?php Snippets_Manager::render_snippet( 'forms/html5' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Datetime elements -->
    <br id="br-text_input" class="clear" />
    <h2><?php _e( 'Datetime elements', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?= sprintf( 'If you creating date time inputs for form for editing <em>custom-</em>post type you can use <b>WordPress</b> function <a href="touch_time" target="blank"><code>touch_time()</code></a> (<b>Warning:</b> This function can be used only on <code>post.php</code> or <code>post-new.php</code> pages!):', 'https://developer.wordpress.org/reference/functions/touch_time/' )?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/datetime-1' ) ?>
	    <?php
	    @touch_time(false, false, false, true);
	    ?>
        <p><?php _e( 'This will create output like this:', ODWPAP_DOMAIN ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/datetime-2' ) ?>
        <p><?php _e( 'Otherwise there are simple date time inputs available:', ODWPAP_DOMAIN ) ?></p>
        <label style="display: inline-block; width: 200px;">Date:</label> <input name="input-date" type="date"><br>
        <label style="display: inline-block; width: 200px;">Month:</label> <input name="input-month" type="month"><br>
        <label style="display: inline-block; width: 200px;">Week:</label> <input name="input-week" type="week"><br>
        <label style="display: inline-block; width: 200px;">Time:</label> <input name="input-time" type="time"><br>
        <label style="display: inline-block; width: 200px;">Local Date and Time:</label> <input name="input-datetime-local" type="datetime-local">
	    <?php Snippets_Manager::render_snippet( 'forms/datetime-3' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Other elements -->
    <br id="br-others" class="clear" />
    <h2><?php _e( 'Other elements', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        Number: <input name="input-number" type="number" min="0" max="20" /><br>
        Range: <input name="input-range" type="range" /><br>
        Color: <input name="input-color" type="color" />
	    <?php Snippets_Manager::render_snippet( 'forms/other-elements' ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Buttons -->
    <br id="br-text_input" class="clear" />
    <h2><?php _e( 'Buttons', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?php printf( __( '<b>WordPress</b> contains helper function for rendering submit buttons %ssubmit_button%s:', ODWPAP_DOMAIN ), '<a href="https://developer.wordpress.org/reference/functions/submit_button/" target="blank"><code>', '</code></a>' ) ?></p>
        <p class="description"><?php _e( 'Note: This function can be used only in administration (is located in file <code>wp-admin/includes/template.php</code>).', ODWPAP_DOMAIN ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/buttons-1' ) ?>
	    <?php submit_button( 'Submit Input', 'primary', 'my-submit' );?>
        <p><?php _e( 'But you can also use plain HTML:', ODWPAP_DOMAIN ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/buttons-2' ) ?>
        <input type="submit" value="Submit Input" class="button" /><br><br>
        <input type="button" value="Secondary Button" class="button-secondary" /><br><br>
        <input type="button" value="Primary Button" class="button-primary" />
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Form table -->
    <br id="br-form_table" class="clear" />
    <h2><?php _e( 'Form table', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?php _e( 'Here is minor excerpt with the form table as is used in <strong>WordPress</strong> options pages.', ODWPAP_DOMAIN ) ?></p>
        <!-- Example: Form table -->
        <table class="form-table">
            <tbody>
            <tr>
                <th scope="row">
                    <label for="input-test-name">Shop name</label>
                </th>
                <td>
                    <fieldset>
                        <legend class="screen-reader-text">
                            <span>Name of one-page shop</span>
                        </legend>
                        <p>
                            <label title="Same as whole WordPress site" data-value="inherited">
                                <input type="radio" name="input-test-name" value="inherited" checked="checked">
                                Same as whole WordPress site
                                <span class="description"> (Same as is inserted <a href="#">here</a>&hellip;)</span>
                            </label>
                        </p>
                        <p>
                            <label title="Custom: " data-value="custom">
                                <input type="radio" name="input-test-name" value="custom">
                                Custom:
                                <span class="screen-reader-text">insert name of shop</span>
                                <label class="screen-reader-text" for="input-test-name_custom">Name of one-page shop</label>
                                <input type="text" name="input-test-name_custom" id="input-test-name_custom" value="" class="regular-text" placeholder="Enter name for your new one-page shop&hellip;" disabled="disabled">
                            </label>
                        </p>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <label for="test-input-02">Description</label>
                </th>
                <td>
                    <fieldset>
                        <p>
                            <label for="test-input-02">Shop's description should be simple and easily to remember.</label>
                            <input type="text" name="test-input-02" id="test-input-02" class="regular-text">
                        </p>
                        <p class="description">Enter text with at the most 255 characters.</p>
                    </fieldset>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript">
            jQuery(document).on("ready", function () {
                jQuery("input[name='input-test-name']").parent().on(
                    "click",
                    function() {
                        if (jQuery(this).data('value') == "custom") {
                            jQuery("#input-test-name_custom")
                                .prop("disabled", false)
                                .removeProp("disabled").focus();
                        } else {
                            jQuery("#input-test-name_custom")
                                .prop("disabled", true);
                        }
                    }
                );
            });
        </script>
        <!-- // Example: Form table -->
	    <?php Snippets_Manager::render_snippet( 'forms/form-table', 'language-php', true ) ?>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- NONCE field -->
    <br id="br-nonce" class="clear" />
    <h2><?php _e( 'NONCE field', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?php printf( 'When you need add security field into your forms you can use <a href="%s" target="blank"><code>wp_nonce_field</code></a> function.', 'https://developer.wordpress.org/reference/functions/wp_nonce_field/' ) ?></p>
	    <?php Snippets_Manager::render_snippet( 'forms/nonce' ) ?>
        <p class="description"><?php printf( '<b>Note:</b> Nonces are described here in article <a href="%s" target="blank">WordPress Nonces</a> (WordPress Codex).', 'https://codex.wordpress.org/WordPress_Nonces' ) ?></p>
    </div>
    <p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

</div><!-- .wrap -->
