<?php
/**
 * WordPress plugin Admin Patterns that contains design patterns library
 * to help with developing plugins that perfectly fit into WordPress.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @link https://github.com/ondrejd/odwp-adminpatterns for the canonical source repository
 * @package odwp-adminpatterns
 * @since 0.2.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

?><div class="wrap">

	<h1><?php _e( 'Gutenberg support', ODWPAP_DOMAIN ) ?></h1>

	<!-- ... -->

</div>