<div class="wrap">
	<?php screen_icon(); ?>

	<h2>Style Helper Classes</h2>

	<div class="wp-pattern-example">
		<h3>Alignment</h3>

		<table class="wp-pattern-table">
		<thead>
			<tr>
				<th class="example-code">Class</th>
				<th class="example-descrip">Description</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><code>.alignleft</code></td>
				<td><span class="alignleft">Elements with left alignment.</span></td>
			</tr>
			<tr>
				<td><code>.alignright</code></td>
				<td><span class="alignright">Elements with rign alignment.</span></td>
			</tr>
		</tbody>
		</table>
	</div>

	<div class="wp-pattern-example">
		<h3>Blocks</h3>

		<table class="wp-pattern-table">
		<thead>
			<tr>
				<th class="example-code">Class</th>
				<th class="example-descrip">Description</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><code>.wp-ui-primary</code></td>
				<td><span class="wp-ui-primary">Elements with this class uses the base color.</span></td>
			</tr>
			<tr>
				<td><code>.wp-ui-highlight</code></td>
				<td><span class="wp-ui-highlight">Elements with this class uses the highlight color.</span></td>
			</tr>
			<tr>
				<td><code>.wp-ui-notification</code></td>
				<td><span class="wp-ui-notification">Elements with this class uses the notification color.</span></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="wp-pattern-example">
		<h3>Text</h3>

		<table class="wp-pattern-table">
		<thead>
			<tr>
				<th class="example-code">Class</th>
				<th class="example-descrip">Description</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><code>.wp-ui-text-primary</code></td>
				<td><span class="wp-ui-text-primary">Text with this class uses the base color.</span></td>
			</tr>
			<tr>
				<td><code>.wp-ui-text-highlight</code></td>
				<td><span class="wp-ui-text-highlight">Text with this class uses the highlight color.</span></td>
			</tr>
			<tr>
				<td><code>.wp-ui-text-notification</code></td>
				<td><span class="wp-ui-text-notification">Text with this class uses the notification color.</span></td>
			</tr>
			<tr>
				<td><code>.wp-ui-text-icon</code></td>
				<td><span class="wp-ui-text-icon">Text with this class uses the icon color.</span></td>
			</tr>
		</tbody>
	</table>
	</div>
</div><!-- .wrap -->
