<?php
/**
 * WordPress plugin Admin Patterns that contains design patterns library
 * to help with developing plugins that perfectly fit into WordPress.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @link https://github.com/ondrejd/odwp-adminpatterns for the canonical source repository
 * @package odwp-adminpatterns
 * @since 0.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

use \com\ondrejd\adminpatterns\Snippets_Manager;

?><div class="wrap">

    <h1><?php _e( 'Other Admin Widgets', ODWPAP_DOMAIN ) ?></h1>

	<h3 class="screen-reader-text"><?php _e( 'List of Contents', ODWPAP_DOMAIN ) ?></h3>
	<ul class="subsubsub">
		<li><b><?php _e( 'Contents:', ODWPAP_DOMAIN ) ?></b> </li>
		<li><a href="#br-admin_notices"><?php _e( 'Admin Notices', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-bubble_icon"><?php _e( 'Bubble Icon', ODWPAP_DOMAIN ) ?></a> | </li>
		<li><a href="#br-spinner"><?php _e( 'Spinner', ODWPAP_DOMAIN ) ?></a> | </li>
        <li><a href="#br-admin_colors"><?php _e( 'Admin Colors', ODWPAP_DOMAIN ) ?></a></li>
	</ul>

	<!-- Admin notices -->
	<br id="br-admin_notices" class="clear" />
	<h2><?php _e( 'Admin notices', ODWPAP_DOMAIN ) ?></h2>
	<div class="wp-pattern-example">
		<p><?php _e( 'When you want to show result of any operation to the user the <b>admin notices</b> are what you looking for. These notifications are allways shown at the top of a page just beneath the main title. Needed markup is simple:', ODWPAP_DOMAIN ) ?></p>
		<?php Snippets_Manager::render_snippet( 'otherwidgets/admin-notices' ) ?>
		<p><?php _e( 'And the resulting notices looks like this:', ODWPAP_DOMAIN ) ?></p>
		<img src="<?php echo ODWPAP_URL . 'assets/images/admin_notices.png' ?>" alt="Example notices"/>
		<p><?php _e( 'As you can see the last notice is also dismissible - this is because of using class <code>.is-dismissible</code>.', ODWPAP_DOMAIN ) ?></p>
	</div>
	<p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

	<!-- Bubble Icon -->
	<br id="br-bubble_icon" class="clear" />
	<h2><?php _e( 'Bubble Icon', ODWPAP_DOMAIN ) ?></h2>
	<div class="wp-pattern-example">
		<p><?php printf( __( 'Sometimes you want to show count of items for an admin menu item (does not matter if it is your menuitem or <em>WP</em> original). It\'s pretty simple you just need to add hook for action %sadmin_menu%s and update any menu item you want: ', ODWPAP_DOMAIN ), '<code><a href="https://codex.wordpress.org/Plugin_API/Action_Reference/admin_menu" target="blank">', '</a></code>' ) ?></p>
		<?php Snippets_Manager::render_snippet( 'otherwidgets/bubble-icon', 'language-php', true ) ?>
		<p><?php _e( 'If you try previous example you will got something like this:', ODWPAP_DOMAIN ) ?></p>
		<img src="<?php echo ODWPAP_URL . 'assets/images/bubble_count.png' ?>" alt="<?php _e( 'Example bubble icon', ODWPAP_DOMAIN ) ?>"/>
	</div>
	<p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

    <!-- Spinners -->
    <br id="br-spinner" />
    <h2><?php _e( 'Spinner', ODWPAP_DOMAIN ) ?></h2>
    <div class="wp-pattern-example">
        <p><?php printf( 'This element is new since <b>WordPress</b> version <b>4.2</b> (<a href="%s" target="blank">more details</a>). Is oftenly used in inline forms while AJAX submitting is performed. See example below:', 'https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/' ) ?></p>
        <p><?php _e( 'Here is an excerpt from required HTML code:', ODWPAP_DOMAIN ) ?></p>
		<?php Snippets_Manager::render_snippet( 'otherwidgets/spinner-html' ) ?>
        <p><?php _e( 'And here is JavaScript code which toggles visibility of the spinner:', ODWPAP_DOMAIN ) ?></p>
		<?php Snippets_Manager::render_snippet( 'otherwidgets/spinner-js', 'language-php', true ) ?>
		<?php
		/**
		 * @todo We need working example!!!
		 */
		?>
        <p class="submit submit-example">
            <button class="button-primary save alignright" type="button">Click me!</button>
            <span class="spinner is-active" style="visibility: collapse;"></span>
        <div class="clear" />
        </p>
    </div>

	<!-- Admin Colors -->
	<br id="br-admin_colors" />
	<h2><?php _e( 'Admin Colors', ODWPAP_DOMAIN ) ?></h2>
	<div class="wp-pattern-example">
		<p><?php _e( 'Here are listed color schemas provided by <strong>WordPress</strong> administration:', ODWPAP_DOMAIN ) ?></p>
		<table class="widefat admin-colors-table">
			<thead>
				<tr>
					<th class="name-col"><?php _e( 'Schema name', ODWPAP_DOMAIN ) ?></th>
					<th colspan="2"><?php _e( 'Colors', ODWPAP_DOMAIN ) ?></th>
				</tr>
			</thead>
			<tbody>
				<?php 
					global $_wp_admin_css_colors;
					$i = 0;
					foreach ( $_wp_admin_css_colors as $color_schema_id => $color_schema ):
						$tr_class =  ( $i % 2 ) ? ' class="alternate"' : '';
				?>
				<tr<?php echo $tr_class; ?>>
					<th rowspan="2" scope="row">
						<span><?php esc_html_e( $color_schema->name ) ?></span>
						<?php if ( get_user_option( 'admin_color' ) == $color_schema_id ):?>
							<br /><small><i><?php _e( '(Currently used)', ODWPAP_DOMAIN ) ?></i></small>
						<?php endif; ?>
					</th>
					<td class="subname-col"><?php _e( 'Base Colors: ', ODWPAP_DOMAIN ) ?></td>
					<td>
						<?php foreach ( $color_schema->colors as $color_id => $color_code ): ?>
						<span title="<?php esc_attr_e( $color_code ) ?>" class="color_example" style="background-color: <?php esc_attr_e( $color_code ) ?>; border: 1px solid <?php esc_attr_e( $color_code ) ?>"></span>
						<?php endforeach;?>
					</td>
				</tr>
				<tr<?php echo $tr_class; ?>>
					<td class="subname-col"><?php _e( 'Icon Colors: ', ODWPAP_DOMAIN ) ?></td>
					<td>
						<?php foreach ( $color_schema->icon_colors as $icon_color_id => $icon_color_code ): ?>
						<span title="<?php esc_attr_e( $icon_color_id . ': ' .$icon_color_code ) ?>" class="color_example color_example-icon" style="background-color: <?php esc_attr_e( $icon_color_code ) ?>; border: 1px solid <?php esc_attr_e( $icon_color_code ) ?>"></span>
						<?php endforeach;?>
					</td>
				</tr>
				<?php $i++; endforeach; ?>
			</tbody>
		</table>
	</div>
	<p class="description"><a href="#wpbody" class="alignright"><?php _e( 'Back to top', ODWPAP_DOMAIN ) ?></a></p>

</div><!-- .wrap -->