<div class="wrap">

	<?php screen_icon(); ?>

	<h2>WordPress Administration Design Patterns Library</h2>

    <p>...</p>

	<h3>Table of Contents</h3>

	<ul class="ul-disc">
	<!-- XXX List all screen ... -->
	</ul>

	<h3>Usefull links</h3>
	<ul class="ul-disc">
		<li><a href="https://developer.wordpress.org/resource/dashicons" target="blank">Developer Resources: Dashicons</a></li>
		<li><a href="https://codex.wordpress.org/Database_Description" target="blank">WordPress Database Description</a></li>
        <li><a href="https://developer.wordpress.org/plugins/the-basics/best-practices/" target="blank">Plugin Handbook</a></li>
	</ul>

</div>